var age, height;
var isLegal = age >= 18;
console.log(isLegal);
var tall = height >=5.11;
console.log(tall);
var suitable = isLegal && tall;
console.log(suitable);
var status;
var isRoyalty =status === 'royalty';
console.log(isRoyalty);
var specialCase = isRoyalty && hasInvitation;
console.log(specialCase);
var canEnterOurBar =suitable || specialCase;
console.log(canEnterOurBar);