var a = 'hello' && '';
console.log('-------');
console.log(a);
var b = '' && [];
console.log('-------');
console.log(b);
var c = undefined && 0;
console.log('-------');
console.log(c);
var d = 1 && 5;
console.log('-------');
console.log(d);
var e = 0 && {};
console.log('-------');
console.log(e);
var f = 'hi' && [] && 'done';
console.log('-------');
console.log(f);
var g = 'bye' && undefined || 'adios';
console.log('-------');
console.log(g);